DROP TABLE IF EXISTS posts CASCADE;
CREATE TABLE posts (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  entry TEXT,
  rating INTEGER NOT NULL,
  photo_link TEXT NOT NULL,
  latitude DECIMAL(8,6) NOT NULL,
  longitude DECIMAL(9,6) NOT NULL,
  locality VARCHAR(255) NOT NULL,
  date_posted TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);